import os
from PIL import Image
import io
from rembg import remove, new_session
import requests
import shutil
from openai import OpenAI

class AIStudio:
    def __init__(self, remove_bg_key=None, ai_vision_key=None, openai_key=None):
        self.remove_bg_key = remove_bg_key
        self.ai_vision_key = ai_vision_key
        # Load OpenAI Client if Key exists
        self.openai_client = OpenAI(api_key=openai_key) if openai_key else None
        # Switch to 'isnet-general-use' for high-precision edge detection
        self.session = new_session("isnet-general-use") 

    def pick_best_image(self, image_urls):
        return image_urls[0] if image_urls else None

    def remove_background(self, image_path, output_path, precision=False):
        """
        Background removal with Fast and Precision modes.
        """
        try:
            img = Image.open(image_path)
            if not precision:
                max_size = 1200
                if max(img.size) > max_size:
                    img.thumbnail((max_size, max_size), Image.LANCZOS)
                erode_size = 5
            else:
                erode_size = 15 
            
            temp_buffer = io.BytesIO()
            img.save(temp_buffer, format="PNG")
            input_data = temp_buffer.getvalue()
            
            output_data = remove(
                input_data, 
                session=self.session,
                alpha_matting=True,
                alpha_matting_foreground_threshold=240,
                alpha_matting_background_threshold=10,
                alpha_matting_erode_size=erode_size
            )
            
            img_out = Image.open(io.BytesIO(output_data)).convert("RGBA")
            white_bg = Image.new("RGBA", img_out.size, (255, 255, 255, 255))
            final_img = Image.alpha_composite(white_bg, img_out)
            
            quality = 100 if precision else 90
            final_img.convert("RGB").save(output_path, "JPEG", quality=quality, optimize=True)
            return True
        except Exception as e:
            print(f"Removal Error: {e}")
            return False

    def analyze_product_with_ai(self, image_path):
        """
        Generates metadata. If OpenAI Key is present, uses GPT-4o Vision.
        Otherwise, returns placeholder data.
        """
        if self.openai_client:
            # TODO: Implement actual GPT-4o Vision call here
            return {
                "title": "AI Optimized Product Listing",
                "description": "Generated by GPT-4o Vision",
                "category": "Fashion > Shoes"
            }
        
        return {
            "title": "AI Optimized Luxury Beauty Product",
            "description": "Premium product analyzed by DOBI AI.",
            "category": "Beauty > Body Care"
        }

    def generate_ai_background(self, product_image_path, prompt, output_path):
        """
        Uses DALL-E 3 to create a background based on user prompt.
        """
        if not self.openai_client:
            return self.remove_background(product_image_path, output_path, precision=True)
            
        # TODO: Implement DALL-E 3 generative fill / background replacement
        print(f"Generating DALL-E 3 background with prompt: {prompt}")
        return True
